# Generated by Django 4.2.6 on 2023-10-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copysite', '0004_remove_author_created_remove_quotes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='born',
            field=models.CharField(max_length=10),
        ),
    ]
