# Generated by Django 4.2.6 on 2023-10-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
