# Generated by Django 4.2.6 on 2023-10-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copysite', '0003_rename_created_at_author_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='created_at',
        ),
    ]
